ktor:
  deployment:
    port: 8080
  application:
    modules:
      - SerializationKt.configureSerialization
      - ExposedKt.configureExposed
      - StatusPagesKt.configureStatusPages
      - RoutingKt.configureRouting
