ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.example.SerializationKt.configureSerialization
      - com.example.ExposedKt.configureExposed
      - com.example.StatusPagesKt.configureStatusPages
      - com.example.RoutingKt.configureRouting
      - com.example.AuthenticationKt.configureAuthentication


jwt:
  secret: "demo_secret"
  issuer: "http://localhost:8080/"
  audience: "http://localhost:8080/"