openapi: 3.0.3
info:
  title: Car Sharing API
  version: "1.0.0"

paths:
  /cars:
    get:
      summary: Haal alle auto's op
      operationId: getAllCars
      tags:
        - Cars
      responses:
        "200":
          description: Lijst van alle auto's
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Car"

components:
  schemas:
    Car:
      oneOf:
        - $ref: "#/components/schemas/ICECar"
        - $ref: "#/components/schemas/BEVCar"
        - $ref: "#/components/schemas/FCEVCar"
      discriminator:
        propertyName: type
        mapping:
          ICECar: "#/components/schemas/ICECar"
          BEVCar: "#/components/schemas/BEVCar"
          FCEVCar: "#/components/schemas/FCEVCar"

    CarBase:
      type: object
      required:
        - id
        - ownerId
        - licensePlate
        - brand
        - model
        - productionYear
        - color
        - seats
      properties:
        id:
          type: integer
          nullable: true
        ownerId:
          type: integer
        licensePlate:
          type: string
        brand:
          type: string
        model:
          type: string
        year:
          type: integer
        trim:
          type: string
          nullable: true
        color:
          type: string
        seats:
          type: integer

    ICECar:
      allOf:
        - $ref: "#/components/schemas/CarBase"
        - type: object
          required:
            - type
            - fuelType
            - tankCapacityL
            - automaticTransmission
          properties:
            type:
              type: string
              enum: [ICECar]
            fuelType:
              type: string
              enum: [PETROL, DIESEL, LPG]
            tankCapacityL:
              type: number
              format: double
            automaticTransmission:
              type: boolean

    BEVCar:
      allOf:
        - $ref: "#/components/schemas/CarBase"
        - type: object
          required:
            - type
            - batteryCapacityKwh
          properties:
            type:
              type: string
              enum: [BEVCar]
            batteryCapacityKwh:
              type: number
              format: double

    FCEVCar:
      allOf:
        - $ref: "#/components/schemas/CarBase"
        - type: object
          required:
            - type
            - tankCapacityKgH2
          properties:
            type:
              type: string
              enum: [FCEVCar]
            tankCapacityKgH2:
              type: number
              format: double